name: py

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip"
      - name: Install Dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt
      - if: ${{ runner.os == 'Windows' }}
        run: powershell.exe -File download_ml_models.ps1
      - if: ${{ runner.os != 'Windows' }}
        run: sh download_ml_models.sh
      - run: python -m pytest --isort --black
